const SAVE_EMAIL = 'SAVE_EMAIL';
const GET_EXPENSE_DATA = 'ADD_EXPENSE_DATA';
const GET_EXPENSE_DATA_SUCCESS = 'ADD_EXPENSE_DATA_SUCCESS';
const GET_CURRENCIES = 'GET_CURRENCIES';
const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';
const ADD_AN_EXPENSE = 'ADD_AN_EXPENSE';
const REMOVE_AN_EXPENSE = 'REMOVE_AN_EXPENSE';
const ENABLE_EDITION = 'ENABLE_EDITION';
const EDIT_AN_EXPENSE = 'EDIT_AN_EXPENSE';

export {
  SAVE_EMAIL,
  GET_EXPENSE_DATA,
  GET_EXPENSE_DATA_SUCCESS,
  GET_CURRENCIES,
  GET_CURRENCIES_SUCCESS,
  ADD_AN_EXPENSE,
  REMOVE_AN_EXPENSE,
  ENABLE_EDITION,
  EDIT_AN_EXPENSE,
};
