const SAVE_EMAIL = 'SAVE_EMAIL';
const ADD_EXPENSE_DATA = 'ADD_EXPENSE_DATA';
const GET_CURRENCIES = 'GET_CURRENCIES';
const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';

export { SAVE_EMAIL, ADD_EXPENSE_DATA, GET_CURRENCIES, GET_CURRENCIES_SUCCESS };
